"""add_investment_position_snapshots_table

Revision ID: 3df91705f917
Revises: 81412d2dafe0
Create Date: 2026-08-04 15:12:32.979523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df91705f917'
down_revision: Union[str, None] = '81412d2dafe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_position_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_held', sa.Float(), nullable=False),
    sa.Column('invested_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', 'date', name='uq_position_snapshots_user_asset_date')
    )
    op.create_index(op.f('ix_investment_position_snapshots_asset_id'), 'investment_position_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_investment_position_snapshots_date'), 'investment_position_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_investment_position_snapshots_id'), 'investment_position_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_investment_position_snapshots_user_id'), 'investment_position_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_position_snapshots_user_id'), table_name='investment_position_snapshots')
    op.drop_index(op.f('ix_investment_position_snapshots_id'), table_name='investment_position_snapshots')
    op.drop_index(op.f('ix_investment_position_snapshots_date'), table_name='investment_position_snapshots')
    op.drop_index(op.f('ix_investment_position_snapshots_asset_id'), table_name='investment_position_snapshots')
    op.drop_table('investment_position_snapshots')
    # ### end Alembic commands ###
