"""add current_price to assets

Revision ID: 81412d2dafe0
Revises: 40acec07887f
Create Date: 2026-08-04 09:29:54.850204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81412d2dafe0'
down_revision: Union[str, None] = '40acec07887f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'current_price')
    # ### end Alembic commands ###
