"""add_dashboard_hidden_widgets_to_user

Revision ID: b56f15af599e
Revises: 67b2f2c35cbc
Create Date: 2026-08-02 19:31:40.622775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56f15af599e'
down_revision: Union[str, None] = '67b2f2c35cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dashboard_hidden_widgets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard_hidden_widgets')
    # ### end Alembic commands ###
